"""TensorForge: A Memory-Aware Deep Learning Framework and Inference Engine."""

from tensorforge import autograd, backend, data, inference, native, nn, optim, quantization, serialization, training
from tensorforge.autograd.engine import backward, is_grad_enabled, no_grad
from tensorforge.backend.dispatcher import (
    backend_context,
    get_backend,
    get_last_backend,
    get_num_threads,
    set_backend,
    set_last_backend,
    set_num_threads,
)
from tensorforge.inference import (
    BufferLifetime,
    CompiledPlanCache,
    ExecutionContext,
    ExecutionContextPool,
    ExecutionPlan,
    ExecutionStep,
    GraphOptimizer,
    InferenceCompiler,
    InferenceGraph,
    InferenceNode,
    InferenceRuntime,
    MemoryPlan,
    MemoryPlanner,
    MemoryRegion,
    ModelLoader,
    OperatorFusionPass,
    PerformanceReport,
    PlannedBuffer,
    ProfileEvent,
    ProfileSession,
    RuntimeProfiler,
    ShapePropagator,
)
from tensorforge.quantization import (
    QuantizedTensor,
    dequantize,
    dequantize_tensor,
    qmatmul,
    quantize,
    quantize_tensor,
)
from tensorforge.serialization import (
    compute_model_size,
    load_checkpoint,
    load_model,
    load_state_dict_from_file,
    save_checkpoint,
    save_model,
)
from tensorforge.tensor.dtype import (
    DType,
    bool_,
    float16,
    float32,
    float64,
    int8,
    int32,
    int64,
    promote_dtypes,
    to_dtype,
    uint8,
)
from tensorforge.tensor.native_storage import NativeStorage, is_native_available
from tensorforge.tensor.operations import (
    add,
    argmax,
    cross_entropy,
    exp,
    log,
    matmul,
    mean,
    mul,
    neg,
    pow,
    relu,
    reshape,
    sigmoid,
    softmax,
    sub,
    sum,
    tanh,
    transpose,
    truediv,
)
from tensorforge.tensor.shape import (
    broadcast_shapes,
    compute_contiguous_strides,
    compute_numel,
)
from tensorforge.tensor.storage import NumPyStorage, Storage
from tensorforge.tensor.tensor import (
    Tensor,
    arange,
    from_numpy,
    ones,
    randn,
    tensor,
    zeros,
)
from tensorforge.utils.validation import (
    ConcurrencyError,
    DimensionError,
    DTypeError,
    ExecutionContextError,
    IndexError_,
    QuantizationError,
    RuntimeClosedError,
    SerializationError,
    ShapeError,
    StorageError,
    TensorForgeError,
)

__version__ = "1.4.0"

__all__ = [
    "__version__",
    # Subpackages
    "nn",
    "autograd",
    "optim",
    "data",
    "training",
    "native",
    "backend",
    "quantization",
    "serialization",
    "inference",
    # Core
    "Tensor",
    "tensor",
    "zeros",
    "ones",
    "randn",
    "arange",
    "from_numpy",
    # Inference Compiler, Memory Planning, Concurrency & Profiling
    "InferenceRuntime",
    "ModelLoader",
    "InferenceGraph",
    "InferenceNode",
    "OperatorFusionPass",
    "GraphOptimizer",
    "InferenceCompiler",
    "ExecutionPlan",
    "ExecutionStep",
    "ExecutionContext",
    "ExecutionContextPool",
    "MemoryPlanner",
    "MemoryPlan",
    "BufferLifetime",
    "MemoryRegion",
    "PlannedBuffer",
    "ShapePropagator",
    "CompiledPlanCache",
    "RuntimeProfiler",
    "ProfileSession",
    "ProfileEvent",
    "PerformanceReport",
    # Serialization
    "save_model",
    "load_model",
    "load_state_dict_from_file",
    "save_checkpoint",
    "load_checkpoint",
    "compute_model_size",
    # Quantization
    "QuantizedTensor",
    "quantize",
    "dequantize",
    "quantize_tensor",
    "dequantize_tensor",
    "qmatmul",
    # Backend & Thread Control
    "set_backend",
    "get_backend",
    "get_last_backend",
    "backend_context",
    "set_num_threads",
    "get_num_threads",
    # Autograd
    "backward",
    "no_grad",
    "is_grad_enabled",
    # DTypes
    "DType",
    "float32",
    "float64",
    "int32",
    "int64",
    "float16",
    "int8",
    "uint8",
    "bool_",
    "to_dtype",
    "promote_dtypes",
    # Storage & Shape
    "Storage",
    "NumPyStorage",
    "NativeStorage",
    "is_native_available",
    "compute_numel",
    "compute_contiguous_strides",
    "broadcast_shapes",
    # Operations
    "add",
    "sub",
    "mul",
    "truediv",
    "neg",
    "matmul",
    "reshape",
    "transpose",
    "sum",
    "mean",
    "exp",
    "log",
    "relu",
    "sigmoid",
    "tanh",
    "softmax",
    "pow",
    "cross_entropy",
    "argmax",
    # Errors
    "TensorForgeError",
    "ShapeError",
    "DimensionError",
    "DTypeError",
    "IndexError_",
    "StorageError",
    "QuantizationError",
    "SerializationError",
    "RuntimeClosedError",
    "ExecutionContextError",
    "ConcurrencyError",
]
